packages:
  - "apps/*"
  - "packages/*"
  - "database"

overrides:
  fastify: 5.11.3
  "@nestjs/swagger>js-yaml": 5.2.2
  "minimatch>brace-expansion": 5.0.9
  "nx>brace-expansion": 5.0.9

allowBuilds:
  "@scarf/scarf": true
  cpu-features: true
  esbuild: true
  msgpackr-extract: true
  nx: true
  protobufjs: true
  ssh2: true
  unrs-resolver: true

onlyBuiltDependencies:
  - "@scarf/scarf"
  - esbuild
  - msgpackr-extract
  - nx
  - unrs-resolver
