apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api
  namespace: saas
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: realtime
  namespace: saas
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: realtime
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: worker
  namespace: saas
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: worker
