server {
  listen 8080;
  server_name app.blupo.com.br;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
    include /etc/nginx/security-headers.inc;
    add_header Cache-Control "no-store" always;
  }

  location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
    expires 1y;
    include /etc/nginx/security-headers.inc;
    add_header Cache-Control "public, immutable" always;
  }
}
